### ISSUE TITLE
[Таблиця кориcтувачів] 'Dots' appear upon click at User if his/her profile is not accessible

### ISSUE THREAD

**Issue by ohumenchuk** [ita-social-projects/EPlast#1176] opened 2021-04-30 12:13 UTC
**Environment:** Windows 8.1 Enterprise, Chrome Version 89.0.4389.114 (Official Build) (64-bit);
**Reproducible:** always;
**Build found:** commit 8179f79;
**Severity:** minor;
**Priority:** high.

**Preconditions:**
Go to https://eplast.westeurope.cloudapp.azure.com/ and log in as any User who has a limited access to **Таблиця користувачів** grid (cannot view all profiles - for example, as 'Дійсний член організації' can see only profiles of Users, who belong to his/her city). Open **Таблиця користувачів** grid by path: **Main Menu/Довідка/Таблиця користувачів.**

**Steps to reproduce:**
1. In **Таблиця користувачів** grid click with right mouse button at any User you do not have access to;
2. Pay attention to the place you clicked at.

**Actual result:**
'Dot' appears at the place of click (please see attachment).

**Expected result:**
'Dots' should not appear at the place of click :-)

![dfdf](https://user-images.githubusercontent.com/81754181/116693370-81216400-a9c6-11eb-910f-b769fd0ce592.PNG)

**Comment by skshetska** [comment] 2021-05-23 14:32
There is bug #1242 and maybe it can consider as a duplicate of this issue.

**Closed** 2021-07-28 06:52 UTC
Labels: Bug, Users Table (Таблиця користувачів), Рівні доступу (Access Levels)
